language: java

jdk:
  - oraclejdk7
  - openjdk7

env:
  global:
    - SONATYPE_USERNAME=p6spy
    - secure: "Eaot/cONtJUyLb0Gw8b75hzSEQEK3gl34mMe6hH+fQBOm7x6YcCx+6Cx3hmQvFVwpb1Q5+VHj9xE3Vk3wMrcaj0R6g4xHVMSSS7CZKbKIqgQlyIDgGTSuil94GGmwpJ9lGu71Re4b6p45K1RUIeW7VPZS+MpY3wNgmSBbozkH40="

before_install:
 - "sudo apt-get update -qq"
 - script/travis/before_install_firebird.sh
 - script/travis/before_install_db2.sh
# - sudo apt-get install -qq pgp

before_script:
 - script/travis/before_script_firebird.sh
 - script/travis/before_script_mysql.sh
 - script/travis/before_script_postgres.sh
 - script/travis/before_script_db2.sh
  
script: mvn -version; if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_JDK_VERSION == "oraclejdk7" ]]; then groovy script/travis/generateMavenSettingsForDeploy.groovy; mvn -Dmaven.test.failure.ignore=true clean test -P travis site:site site:stage; mvn -N ghSite:site; else mvn clean test -P travis; fi;

after_script:
 - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_JDK_VERSION == "oraclejdk7" ]]; then groovy script/travis/generateMavenSettingsForDeploy.groovy; mvn clean deploy -DskipTests --settings ~/.m2/deploySettings.xml; fi

notifications:
 email:
   - p6spy-developers@googlegroups.com